AWSTemplateFormatVersion: "2010-09-09"
Description: HAB-Home Automation Backend, Provision & Deploy Infrastructure Pipeline

Parameters:
  ServiceName:
    Type: String
    Default: 'ha-backend'
    Description: Pipeline service to provision and deploy Home Automation app backend
  ECRImageRepository:
    Type: String
    Default: 'home-automation-backend-ecr'
    Description: ECR repository for images
  RepositoryName:
    Type: String
    Default: 'home-automation-prov-deploy-infra-amp'
    Description: CodeCommit repository name for the application code
  BranchName:
    Type: String
    Default: 'main'
    Description: Branch name for the CodeCommit repository
  ImageTag:
    Type: String
    Default: 'latest'
    Description: Docker image tag for the application
  TerraformVersion:
    Type: String
    Default: '1.14.3'
    Description: Version of Terraform to use
  TerraformSha256:
    Type: String
    Default: '178b2a602251bb68b94732aceca2cc1023d87597cb83dba92cab31b6689edb4d'
    Description: SHA256 checksum for the Terraform binary
  Environment:
    Type: String
    Default: 'dev'
    AllowedValues: [ dev, sit, prod ]

Resources:
  TFStateBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ServiceName}-${Environment}-tf-state"
      VersioningConfiguration: { Status: Enabled }

  BuildArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ServiceName}-${Environment}-artifacts"
      VersioningConfiguration: { Status: Enabled }

  TerraformLockTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: LockID
          AttributeType: S
      KeySchema:
        - AttributeName: LockID
          KeyType: HASH
      TableName: !Sub "${ServiceName}-${Environment}-tf-state-lock"
  EC2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
                - ecs.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - !Ref EC2InstanceRolePolicy
        - !Sub 'arn:aws:iam::${AWS::AccountId}:policy/amp-deny-policy'
        - 'arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore'

      RoleName: !Sub "${ServiceName}-${Environment}-EC2InstanceRole"
      PermissionsBoundary: !Sub "arn:aws:iam::${AWS::AccountId}:policy/amp-permissions-boundary"


  EC2InstanceRolePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy for EC2 Instance Role to access S3 and ECR
      Path: "/"
      ManagedPolicyName: !Sub "${ServiceName}-${Environment}-EC2InstanceRolePolicy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - 's3:*'
              - 'ecr:*'
              - 'ecs:*'
              - 'cloudformation:*'
              - 'autoscaling:*'
              - 'iam:PassRole'
              - 'iam:CreateRole'
              - 'iam:ListInstanceProfiles'
              - 'iam:AddRoleToInstanceProfile'
              - 'iam:CreateInstanceProfile'
              - 'cloudwatch:*'
              - 'elasticloadbalancing:*'
              - 'elasticcache:*'
              - 'elasticBeanstalk:*'
              - 'ec2:*'
            Resource: "*"

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - !Ref EC2InstanceRole
      InstanceProfileName: !Sub "${ServiceName}-${Environment}-EC2InstanceProfile"

  ECSRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - 'sts:AssumeRole'
            Principal:
              Service:
                - 'ecs.amazonaws.com'
                - 'ecs-tasks.amazonaws.com'
                - 'ec2.amazonaws.com'
                - 'ssm.amazonaws.com'
                - 'codebuild.amazonaws.com'
                - 'cloudformation.amazonaws.com'
                - 'config.amazonaws.com'
                - 'codepipeline.amazonaws.com'
      Path: /
      ManagedPolicyArns:
        - !Ref ECSAccessPolicy
        - !Sub 'arn:aws:iam::${AWS::AccountId}:policy/amp-deny-policy'
        - arn:aws:iam::aws:policy/AmazonECS_FullAccess
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/CloudWatchFullAccess
        - arn:aws:iam::aws:policy/AmazonSSMFullAccess
      RoleName: !Sub "${ServiceName}-${Environment}-ECSRole"
      PermissionsBoundary: !Sub "arn:aws:iam::${AWS::AccountId}:policy/amp-permissions-boundary"


  ECSAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy for ECS Role to access ECR and S3
      Path: "/"
      ManagedPolicyName: !Sub "${ServiceName}-${Environment}-ECSRolePolicy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Resource:
              - '*'
            Action:
              - 'ssm:PutParameter'
              - 'ssm:GetParameterByPath'
          - Effect: Allow
            Action:
              - 'cloudformation:ListExports'
            Resource: "*"
          - Effect: Allow
            Action:
              - 'ecs:*'
              - 'ecr:*'
              - 's3:*'
              - 'elasticfilesystem:*'
              - 'ec2:*'
              - 'elasticloadbalancing:*'
              - 'autoscaling:*'
              - 'servicediscovery:*'
              - 'iam:*'
              - 'cloudwatch:*'
              - 'cloudformation:*'
              - 'kms:*'
              - 'iam:UpdateAssumeRolePolicy'
              - 'logs:*'
            Resource: "*"
          - Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:GetObjectVersion
            Resource:
              - !Sub "arn:aws:s3:::${BuildArtifactsBucket}/*"
          - Effect: Allow
            Action:
              - 'ecr:GetAuthorizationToken'
              - 'ecr:BatchCheckLayerAvailability'
              - 'ecr:CompleteLayerUpload'
              - 'ecr:InitiateLayerUpload'
              - 'ecr:PutImage'
              - 'ecr:UploadLayerPart'
            Resource: !Sub "arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/${ECRImageRepository}"

  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - !Ref CodeBuildAccessPolicy
        - !Sub 'arn:aws:iam::${AWS::AccountId}:policy/amp-deny-policy'
        - 'arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess'
      RoleName: !Sub '${ServiceName}-${Environment}-CodeBuildRole'
      PermissionsBoundary: !Sub "arn:aws:iam::${AWS::AccountId}:policy/amp-permissions-boundary"

  CodeBuildAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy for CodeBuild to access ECR and S3
      Path: "/"
      ManagedPolicyName: !Sub "${ServiceName}-${Environment}-CodeBuildRole"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - 'logs:CreateLogGroup'
              - 'logs:CreateLogStream'
              - 'logs:PutLogEvents'
            Resource:
              - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${AWS::StackName}*'
              - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${AWS::StackName}-image:*'
          - Effect: Allow
            Action:
              - 's3:GetObject'
              - 's3:GetObjectVersion'
              - 's3:PutObject'
            Resource:
              - !Sub 'arn:aws:s3:::${BuildArtifactsBucket}/*'

          - Effect: Allow
            Action:
              - 'ecr:GetAuthorizationToken'
              - 'ecr:BatchCheckLayerAvailability'
              - 'ecr:CompleteLayerUpload'
              - 'ecr:InitiateLayerUpload'
              - 'ecr:PutImage'
              - 'ecr:UploadLayerPart'
            Resource:
              - !Sub "arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/${ECRImageRepository}"

  CloudFormationExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - !Ref CFNPipelineExecutionPolicy
        - !Sub 'arn:aws:iam::${AWS::AccountId}:policy/amp-deny-policy'
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
        - 'arn:aws:iam::aws:policy/IAMFullAccess'
      RoleName: !Sub '${ServiceName}-${Environment}-CloudFormationExecutionRole'
      PermissionsBoundary: !Sub "arn:aws:iam::${AWS::AccountId}:policy/amp-permissions-boundary"


  CFNPipelineExecutionPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy for CloudFormation Pipeline Execution Role
      Path: "/"
      ManagedPolicyName: !Sub "${ServiceName}-${Environment}-CFNExecutionPolicy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - 'cloudformation:*'
              - 'codepipeline:UpdatePipeline'
              - 'codepipeline:GetPipeline'
              - 'codebuild:StartBuild'
              - 'codebuild:BatchGetBuilds'
              - 'codebuild:UpdateProject'
              - 'codebuild:CreateProject'
              - 'codebuild:DeleteProject'
              - 'codebuild:BatchGetProjects'
              - 'codebuild:ListProjects'
              - 'ec2:*'
              - 's3:*'
              - 'apigateway:POST'
              - 'iam:*'
            Resource: "*"
          - Effect: "Allow"
            Action:
              - 'dynamodb:DescribeTable'
              - 'dynamodb:DeleteTable'
              - 'dynamodb:ListTables'
            Resource: '*'

  PipelineExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - !Ref CFNPipelinePolicy
        - !Ref CodePipelineAccessPolicy
        - 'arn:aws:iam::aws:policy/AWSCodeCommitFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
        - !Sub 'arn:aws:iam::${AWS::AccountId}:policy/amp-deny-policy'
      RoleName: !Sub '${ServiceName}-${Environment}-PipelineExecutionRole'
      PermissionsBoundary: !Sub "arn:aws:iam::${AWS::AccountId}:policy/amp-permissions-boundary"


  CodePipelineAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy for CloudFormation Pipeline Access Role
      Path: "/"
      ManagedPolicyName: !Sub "${ServiceName}-${Environment}-CFNPipelineAccessPolicy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - 'iam:PassRole'
              - 'iam:GetPolicy'
              - 'codepipeline:GetPipeline'
            Resource:
              - "*"
          - Effect: Allow
            Action:
              - 'codebuild:StartBuild'
              - 'codebuild:BatchGetBuilds'
            Resource:  "*"

  CFNPipelinePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: CloudFormation Pipeline Execution Policy
      Path: "/"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 'cloudformation:*'
            Resource: "*"

  ProvisionAndDeployProject:
    DependsOn: CloudFormationExecutionRole
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub '${AWS::StackName}-InvokeTerraformBuild'
      ServiceRole: !GetAtt [ CodeBuildServiceRole, Arn ]
      TimeoutInMinutes: 10
      Artifacts: { Type: CODEPIPELINE }
      Environment:
        ComputeType: 'BUILD_GENERAL1_SMALL'
        Image: aws/codebuild/amazonlinux-x86_64-standard:5.0
        Type: 'LINUX_CONTAINER'
        PrivilegedMode: true
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Sub |
          version: 0.2
          env:
            shell: bash
          phases:
            build:
              commands:
                - echo "Building infrastructure..."
                - yum install -y jq dos2unix
                - cd /tmp && curl -o terraform.zip https://releases.hashicorp.com/terraform/${TerraformVersion}/terraform_${TerraformVersion}_linux_amd64.zip && echo "${TerraformSha256}  terraform.zip" | sha256sum -c --quiet && unzip terraform.zip && mv terraform /usr/bin/ && rm terraform.zip
            post_build:
              commands:
                - pwd
                - cd ..; curl 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI | jq 'to_entries | [ .[] | select(.key | (contains("Expiration") or contains("RoleArn") | not)) ] | map(if .key == "AccessKeyId" then . + {"key":"AWS_ACCESS_KEY_ID"} else . end) | map(if .key == "SecretAccessKey" then . + {"key":"AWS_SECRET_ACCESS_KEY"} else . end) | map(if .key == "Token" then . + {"key":"AWS_SESSION_TOKEN"} else . end) | map("export \(.key)=\(.value)") | .[]' -r > /tmp/aws_cred_export.txt
                - pwd;ls -ltr; 
                - source /tmp/aws_cred_export.txt
                - which dos2unix
                - echo "Moving to source directory"
                - cd $CODEBUILD_SRC_DIR
                - pwd
                - ls -
                - echo "Executing run.sh"
                - cd scripts; pwd; ls -ltr; dos2unix run.sh; chmod +x run.sh; source /tmp/aws_cred_export.txt; bash -x run.sh
                - pwd
                - exit
          artifacts:
              files:
                - 'pipeline/*'
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub "${ServiceName}-${Environment}-pipeline"
      RoleArn: !GetAtt [ PipelineExecutionRole, Arn ]
      ArtifactStore:
        Type: S3
        Location: !Ref BuildArtifactsBucket
      Stages:
        - Name: Source
          Actions:
            - Name: FetchSource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: 1
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                RepositoryName: !Ref RepositoryName
                BranchName: !Ref BranchName
              RunOrder: 1
        - Name: ApprovalAndImagePromotion
          Actions:
            - Name: SeekApproval
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: 1
              Configuration:
                CustomData: !Sub "Please approve the deployment to ${Environment} environment."
              RunOrder: 1
        - Name: Pipeline
          Actions:
            - Name: DeployPipeline
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: !Ref 'AWS::StackName'
                Capabilities: CAPABILITY_NAMED_IAM
                RoleArn: !GetAtt CloudFormationExecutionRole.Arn
                TemplatePath: SourceOutput::pipeline/home-automation-infra-pipeline.yml
              InputArtifacts:
                - Name: SourceOutput
              RunOrder: 1
        - Name: ProvisionAndDeploy
          Actions:
            - Name: ProvisionAndDeployInfra
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: InvokeTerraformOutput
              Configuration:
                ProjectName: !Ref ProvisionAndDeployProject
              RunOrder: 1

#Outputs:
#  ECSRoleName:
#    Description : "Name ECSRole"
#    Value: !Ref ECSRole
#    Export:
#      Name: !Sub ECSRole
#  ECSRoleArn:
#    Description: "ARN of ECSRole"
#    Value: !Ref ECSRoleArn
#    Export:
#      Name: !Sub ECSRoleArn
#  ECSRoleProfile:
#    Description: "Name EC2InstanceProfile"
#    Value: !Ref EC2InstanceProfile
#    Export:
#      Name: !Sub EC2InstanceProfile
